# Generated by Django 5.0.6 on 2024-06-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_rename_users_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='cover_image',
        ),
    ]
