# Generated by Django 5.0.6 on 2024-06-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_public',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
