# Generated by Django 5.0.6 on 2024-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_blog_is_public_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
